In [1]:
"""
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, 
для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))
"""
import numpy as np

N=int(input())
x=np.arange(N-1, -1, -1)
print(x)

4
[3 2 1 0]


In [6]:
"""
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
"""
import numpy as np
N=int(input())
mat=np.diag(np.arange(N-1, -1, -1))
sum_of_diagonal_elements=np.trace(mat)
print(mat)
print('Cумма значений на диагонали матрицы =',sum_of_diagonal_elements)

5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Cумма значений на диагонали матрицы = 10


In [9]:
"""
Задание 3:

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""
from numpy import linalg

a=np.array([[4, 2, 1], [2, 3, 1], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)


array([ -0.22727273,   7.54545455, -10.18181818])

In [14]:
"""
Задание 4

Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров 
этим пользователем.

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим
пользователем и всеми пользователями из массива user_stats
"""
import matplotlib.pyplot as plt

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
shape_of_matrix = users_stats.shape
x,y=shape_of_matrix 


6